import React, { useRef, useState } from "react";
import Head from "next/head";
import "@rainbow-me/rainbowkit/styles.css";
import {
  getDefaultWallets,
  RainbowKitProvider,
  ConnectButton,
  useConnectModal,
} from "@rainbow-me/rainbowkit";
import {
  configureChains,
  createClient,
  useSignMessage,
  WagmiConfig,
} from "wagmi";
import { mainnet, polygon, optimism, arbitrum } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
import * as Comlink from "comlink";
import { FunctionComponent, ReactNode, useEffect } from "react";
import { useAccount, useSigner } from "wagmi";
import { Signer } from "ethers";
import { fetchSigner } from "@wagmi/core";

const { chains, provider } = configureChains(
  [mainnet, polygon, optimism, arbitrum],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  chains,
});

const wagmiClient = createClient({
  autoConnect: false,
  connectors,
  provider,
});

/* const domain =
 *   process.env.NEXT_PUBLIC_SERVER_DOMAIN ||
 *   "https://next-iframe-poc-server.vercel.app/a";
 *  */

const domain = "http://localhost:3001/receiver";

export default function Home() {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>Next IFrame Poc Client</h1>
          <iframe height="800" width="800" src={domain} />
        </main>
        <WalletExample>
          <ConnectButton />
        </WalletExample>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

interface IRemoteActions {
  con: (isConnected: boolean, address: string, signer: any) => void;
}

let signerSet = false;
let init = false;
let init2 = false;
const WalletExample: FunctionComponent<{
  children: ReactNode;
}> = ({ children }) => {
  const { address, isConnected } = useAccount();
  const { data: signer } = useSigner();
  const { signMessageAsync } = useSignMessage();
  const { openConnectModal } = useConnectModal();
  useEffect(() => {
    if (init) {
      return;
    } else {
      init = true;
      Comlink.expose(
        {
          connect: () => {
            openConnectModal && openConnectModal();
          },
          async sign(message: string, cb: (value: string) => void) {
            cb(await signMessageAsync({ message }));
          },
        },
        Comlink.windowEndpoint(window)
      );
    }
  }, [openConnectModal, signMessageAsync]);

  useEffect(() => {
    try {
      Comlink.expose(
        {
          async xmtp(cb: (wallet: Signer) => void) {
            cb(Comlink.proxy(signer));
          },
        },
        Comlink.windowEndpoint(window)
      );
    } catch (e) {
      console.error("error, HOST", { e });
    }
  }, [signer, isConnected]);

  const [actions, setActions] = useState<IRemoteActions | null>(null);
  useEffect(() => {
    const iframe = document.querySelector("iframe");
    if (!init2 || !iframe?.contentWindow) {
      init2 = true;
      setTimeout(() => {
        setActions(() => {
          return Comlink.wrap<IRemoteActions>(
            Comlink.windowEndpoint(iframe!.contentWindow!)
          );
        });
      }, 1000);
    }
  }, []);

  useEffect(() => {
    if (actions && !signerSet) {
      actions.con(isConnected, address as string, null);
      if (signer && !signerSet) {
        actions.con(isConnected, address as string, Comlink.proxy(signer));
        signerSet = true;
      }
    }
  }, [actions, isConnected, address, signer]);

  return <>{children}</>;
};
